membership/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('web.urls', namespace='member')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from django.conf.urls import url, handler404, handler500
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^booking/$', views.booking, name='booking'),
    url(r'^booking_activity/$', views.booking_activity, name='booking_activity'),
    url(r'^handle_booking_activity/$', views.handle_booking_activity, name='handle_booking_activity'),
    url(r'^superadminactivity/$', views.superadminactivity, name='superadminactivity'),
    url(r'^superadmin/$', views.superadmin, name='superadmin'),
    url(r'^superadmin/create/$', views.accommodation_create, name='accommodationCreate'),
    url(r'^superadmin/(?P<pk>\d+)/update/$', views.accommodation_update, name='accommodation_update'),
    url(r'^superadmin/(?P<pk>\d+)/delete/$', views.accommodation_delete, name='accommodation_delete'),
    url(r'^index_search/$', views.search, name='search'),
    url(r'^index_search_activity/$', views.search_activity, name='search_activity'),
    url(r'^search/$', views.accommodation_autocomplete, name='accommodation_autocomplete'),
    url(r'^search_activity/$', views.activity_autocomplete, name='activity_autocomplete'),
    url(r'^cancel_booking/(?P<reservation_no>[0-9A-Za-z_\-]+)/$', views.cancel_booking, name='cancel_booking'),
    url(r'^cancel_booking_activity/(?P<reservation_no>[0-9A-Za-z_\-]+)/$', views.cancel_booking_activity, name='cancel_booking_activity'),
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^invoice/$', views.handle_invoice, name='invoice'),
    url(r'^accommodation_invoice/$', views.handle_invoice_accommodation, name='accommodation_invoice'),
    url(r'^activity_invoice/$', views.handle_invoice_activity, name='activity_invoice'),
    url(r'^invoice/download/(?P<bidb64>[0-9A-Za-z_\-]+)/$', views.invoice_download, name='invoice_download'),
    url(r'^activity_invoice/download/(?P<bidb64>[0-9A-Za-z_\-]+)/$', views.activity_invoice_download, name='activity_invoice_download'),
    url(r'^accommodation/$', views.accommodation, name='accommodation'),
    url(r'^accommodation/(?P<checkin>\d{4}-\d{2}-\d{2})&(?P<checkout>\d{4}-\d{2}-\d{2})/$', views.get_availability, name='get_availability'),
    url(r'^activity/(?P<name>[\w|\W]+)/(?P<date>\d{2}-\d{2}-\d{4})/$', views.get_availability_activity, name='get_availability_activity'),
    url(r'^forgotpassword/$', views.forgotpassword, name='forgotpassword'),
    url(r'^handle_booking/$', views.handle_booking, name='handle_booking'),
    url(r'^reset_new_password/(?P<uidb64>[0-9A-Za-z_\-]+)-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.reset_password, name='resetpassword'),
    url(r'^accommodation_detail/$', views.accommodationdetail, name='accommodationdetail'),
    url(r'^edit_user_info_profile/$', views.edit_user_info_profile, name='edit_user_info_profile'),
    url(r'^edit_address_profile/$', views.edit_address_profile, name='edit_address_profile'),
    url(r'^edit_profile_picture/$', views.edit_profile_picture, name='edit_profile_picture'),
]


handler404 = views.handler404
handler500 = views.handler500

templates/include/footer.html
{% load staticfiles %}

<footer id="footer" class="dark">
    <div class="primary-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="f-logo-center">
                        <a href="{% url 'member:index' %}" class="m-bot-20 footer-logo">
                        <img src="{% static 'img/logo-dark.png' %}" class="retina img-center"  alt="">
                    </a>
                    </div>
                    <p class="">vKirirom Pine Resort is located amongst the pine trees of Kirirom Mountain. Here at vKiriom, we try to preserve the natural beauty of the environment. Our building locations are properly studied so that we avoid cutting down many trees.</p>
                </div>
                {% comment %}<div class="col-md-3">
                    <h3 class="">Kirirom Institute of Technology</h3>
                    <p>KITadapts a new style of learning with an effective new educational techniques as a boarding school.</p>
                    <span><a href="">Enroll here!!</a></span>
                    <p>New university for the future in Kirirom Mountain under the vKririom Project. An educational approach that stands amongst the forest.</p>
                    <span><a href="">More About KIT</a></span>
                </div>{% endcomment %}
                <div class="col-md-4">
                    <h3 class="text-center" style="color: white">THE MEANING OF OUR LOGO</h3>
                    <p>In the logo of vKirirom - you will find '<span style="color: orange;">v</span>' in orange and '<span style="color: green;">Kirirom</span>' in green. The orange colour represents the people who live in Kirirom. This is the colour of joy and creativity. It also reminds us of the robes monks wear in Cambodia. The green represents the nature and its beauty.</p>
                </div>
                <div class="col-md-4">
                    <h3 class="text-center" style="color: white;">STAY CONNECTED</h3>
                    {% comment %}<iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="380" height="250" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>{% endcomment %}
                </div>
            </div>
        </div>
    </div>
    <div class="secondary-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <span class="m-top-10">Copyright @2017 by <a href="#" class="f-link">Kirirom Institute of Technology</a> | All Rights Reserved</span>
                    </div>
                    <div class="col-md-6">
                        <div class="social-link circle pull-right">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-youtube"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</footer>

templates/include/navbar.html
{% load staticfiles %}

{#header start#}
        <header id="header" class="header-full-width sticky">
            <div class="header-sticky light-header">
                <div class="container">
                    <div id="massive-menu" class="menuzord">
                        {# logo start #}
                        <a href="{% url 'member:index' %}" class="logo-brand">
                            <img src="{% static 'img/logo.png' %}" class="retina" alt="">
                        </a>
                        {# logo end #}

                        {# menu start #}

                        <ul class="menuzord-menu pull-left">
                            <li><a href="{% url 'member:index' %}"></a></li>
                        </ul>

                        {% comment %}Left navbar{% endcomment %}
                        <ul class="menuzord-menu pull-right">
                            <li><a href="{% url 'member:accommodation' %}">Accommodation</a></li>
                            <li><a href="{% url 'member:activity' %}">Activity</a></li>
                            <li>
                                {% if user.name %}
                                    <a href="{% url 'member:profile' %}">{{ user.name }}</a>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'member:invoice' %}">Book's Invoice</a></li>
                                        <li><a href="{% url 'member:logout' %}">Logout</a></li>
                                    </ul>
                                {% else %}
                                    <a href="{% url 'member:login' %}">Login/Register</a>
                                    <ul class="dropdown">
                                        <li><a href="{% url 'member:login' %}">Login</a></li>
                                        <li><a href="{% url 'member:register' %}">Register</a></li>
                                    </ul>
                                {% endif %}
                            </li>
                            <li class="nav-icon nav-divider">
                                <a href="javascript:void(0)">|</a>
                            </li>
                            <li><a href="">Book Now</a></li>
                        </ul>
                        {# menu end #}
                    </div>
                </div>
            </div>
        </header>
        {# End header #}

templates/include/partial_book_create.html
{% load widget_tweaks %}

<form method="post" action="{%  url 'accommodationCreate' %}" class="js-acc-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new accommodation</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create Accommodation</button>
  </div>
</form>

templates/include/slider.html
{% load staticfiles %}

{# Slider Start #}
<section class="slider-revulation-wrapper">
    <div class="tp-banner-container">
        <div class="tp-banner">
            <ul>
                {# slide 1 start #}
                <li class=""
                    data-transition="fade"
                    data-slotamount="7"
                    data-masterspeed="500"
                    data-saveperformance="on"
                    data-title="Well Packaged">

                    <img src="{% static 'img/bungalow.JPG' %}" alt="" data-bgposition="center top"
                         data-bgfit="cover" data-bgrepeat="no-repeat">

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption customin customout rev-heading" data-x="100" data-y="150" data-speed="500"
                         data-start="1900" data-easing="Back.easeOut"
                         data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-splitin="" data-splitout="" data-elementdelay="0.1" data-endelementdelay="0.1">Full
                        Responsive
                    </div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption rev-desc fade" data-x="100" data-y="250" data-speed="500" data-start="2700"
                         data-easing="Back.easeOut" data-splitin="" data-splitout="" data-elementdelay="0.1"
                         data-endelementdelay="0.1">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil
                        quisquam dolores vero,
                        <br>laboriosam. Modi quidem optio ea, tenetur a atque eligendi saepe ipsum,
                        <br>ratione laboriosam culpa, vitae, excepturi temporibus eum.
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption rev-subheading sfr" data-x="100" data-y="380" data-speed="500"
                         data-start="3200" data-easing="Back.easeOut" data-splitin="" data-splitout=""
                         data-elementdelay="0.1" data-endelementdelay="0.1">
                        <a href="#" class="btn btn-medium btn-theme-color"><i class="fa fa-shopping-cart"></i> Purchasenow</a>
                    </div>

                </li>
                {# slide 1 End #}
                {# slide 1 start #}
                <li class=""
                    data-transition="fade"
                    data-slotamount="7"
                    data-masterspeed="500"
                    data-saveperformance="on"
                    data-title="Well Packaged">

                    <img src="{% static 'img/bungalow.JPG' %}" alt="" data-bgposition="center top"
                         data-bgfit="cover" data-bgrepeat="no-repeat">

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption customin customout rev-heading" data-x="100" data-y="150" data-speed="500"
                         data-start="1900" data-easing="Back.easeOut"
                         data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-splitin="" data-splitout="" data-elementdelay="0.1" data-endelementdelay="0.1">Full
                        Responsive
                    </div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption rev-desc fade" data-x="100" data-y="250" data-speed="500" data-start="2700"
                         data-easing="Back.easeOut" data-splitin="" data-splitout="" data-elementdelay="0.1"
                         data-endelementdelay="0.1">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil
                        quisquam dolores vero,
                        <br>laboriosam. Modi quidem optio ea, tenetur a atque eligendi saepe ipsum,
                        <br>ratione laboriosam culpa, vitae, excepturi temporibus eum.
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption rev-subheading sfr" data-x="100" data-y="380" data-speed="500"
                         data-start="3200" data-easing="Back.easeOut" data-splitin="" data-splitout=""
                         data-elementdelay="0.1" data-endelementdelay="0.1">
                        <a href="#" class="btn btn-medium btn-theme-color"><i class="fa fa-shopping-cart"></i> Purchasenow</a>
                    </div>

                </li>
                {# slide 1 End #}
                {# slide 1 start #}
                <li class=""
                    data-transition="fade"
                    data-slotamount="7"
                    data-masterspeed="500"
                    data-saveperformance="on"
                    data-title="Well Packaged">

                    <img src="{% static 'img/bungalow.JPG' %}" alt="" data-bgposition="center top"
                         data-bgfit="cover" data-bgrepeat="no-repeat">

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption customin customout rev-heading" data-x="100" data-y="150" data-speed="500"
                         data-start="1900" data-easing="Back.easeOut"
                         data-customin="x:0;y:0;z:0;rotationX:90;rotationY:0;rotationZ:0;scaleX:1;scaleY:1;skewX:0;skewY:0;opacity:0;transformPerspective:200;transformOrigin:50% 0%;"
                         data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                         data-splitin="" data-splitout="" data-elementdelay="0.1" data-endelementdelay="0.1">Full
                        Responsive
                    </div>

                    <!-- LAYER NR. 1 -->
                    <div class="tp-caption rev-desc fade" data-x="100" data-y="250" data-speed="500" data-start="2700"
                         data-easing="Back.easeOut" data-splitin="" data-splitout="" data-elementdelay="0.1"
                         data-endelementdelay="0.1">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil
                        quisquam dolores vero,
                        <br>laboriosam. Modi quidem optio ea, tenetur a atque eligendi saepe ipsum,
                        <br>ratione laboriosam culpa, vitae, excepturi temporibus eum.
                    </div>

                    <!-- LAYER NR. 3 -->
                    <div class="tp-caption rev-subheading sfr" data-x="100" data-y="380" data-speed="500"
                         data-start="3200" data-easing="Back.easeOut" data-splitin="" data-splitout=""
                         data-elementdelay="0.1" data-endelementdelay="0.1">
                        <a href="#" class="btn btn-medium btn-theme-color"><i class="fa fa-shopping-cart"></i> Purchasenow</a>
                    </div>

                </li>
                {# slide 1 End #}
            </ul>
        </div>
    </div>
</section>
{# Slider End #}