membership/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('web.urls', namespace='member')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/urls.py
from django.conf.urls import url, handler404, handler500
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^booking/$', views.booking, name='booking'),
    url(r'^booking_activity/$', views.booking_activity, name='booking_activity'),
    url(r'^handle_booking_activity/$', views.handle_booking_activity, name='handle_booking_activity'),
    url(r'^superadminactivity/$', views.superadminactivity, name='superadminactivity'),
    url(r'^superadmin/$', views.superadmin, name='superadmin'),
    url(r'^superadmin/create/$', views.accommodation_create, name='accommodationCreate'),
    url(r'^superadmin/(?P<pk>\d+)/update/$', views.accommodation_update, name='accommodation_update'),
    url(r'^superadmin/(?P<pk>\d+)/delete/$', views.accommodation_delete, name='accommodation_delete'),
    url(r'^index_search/$', views.search, name='search'),
    url(r'^index_search_activity/$', views.search_activity, name='search_activity'),
    url(r'^search/$', views.accommodation_autocomplete, name='accommodation_autocomplete'),
    url(r'^search_activity/$', views.activity_autocomplete, name='activity_autocomplete'),
    url(r'^cancel_booking/(?P<reservation_no>[0-9A-Za-z_\-]+)/$', views.cancel_booking, name='cancel_booking'),
    url(r'^cancel_booking_activity/(?P<reservation_no>[0-9A-Za-z_\-]+)/$', views.cancel_booking_activity, name='cancel_booking_activity'),
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^invoice/$', views.handle_invoice, name='invoice'),
    url(r'^accommodation_invoice/$', views.handle_invoice_accommodation, name='accommodation_invoice'),
    url(r'^activity_invoice/$', views.handle_invoice_activity, name='activity_invoice'),
    url(r'^invoice/download/(?P<bidb64>[0-9A-Za-z_\-]+)/$', views.invoice_download, name='invoice_download'),
    url(r'^activity_invoice/download/(?P<bidb64>[0-9A-Za-z_\-]+)/$', views.activity_invoice_download, name='activity_invoice_download'),
    url(r'^accommodation/$', views.accommodation, name='accommodation'),
    url(r'^accommodation/(?P<checkin>\d{4}-\d{2}-\d{2})&(?P<checkout>\d{4}-\d{2}-\d{2})/$', views.get_availability, name='get_availability'),
    url(r'^activity/(?P<name>[\w|\W]+)/(?P<date>\d{2}-\d{2}-\d{4})/$', views.get_availability_activity, name='get_availability_activity'),
    url(r'^forgotpassword/$', views.forgotpassword, name='forgotpassword'),
    url(r'^handle_booking/$', views.handle_booking, name='handle_booking'),
    url(r'^reset_new_password/(?P<uidb64>[0-9A-Za-z_\-]+)-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.reset_password, name='resetpassword'),
    url(r'^accommodation_detail/$', views.accommodationdetail, name='accommodationdetail'),
    url(r'^edit_user_info_profile/$', views.edit_user_info_profile, name='edit_user_info_profile'),
    url(r'^edit_address_profile/$', views.edit_address_profile, name='edit_address_profile'),
    url(r'^edit_profile_picture/$', views.edit_profile_picture, name='edit_profile_picture'),
]


handler404 = views.handler404
handler500 = views.handler500

templates/accommodation_invoice.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Invoice</title>
{% endblock %}

{% block content %}
    {% include 'include/navbar.html' %}

    <!--page title start-->
    <section class="page-title page-title-center">
        <div class="container">
            <h2 class="text-uppercase">Profile</h2>
        </div>
    </section>
    <!--page title end-->

    <div class="page-wrapper">
        <div class="main">
            <div class="main-inner">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4 col-lg-3">
                            <div class="sidebar">
                                <div class="widget">
                                    <form id="img-form" action="{% url 'member:edit_profile_picture' %}" method="post"
                                          enctype="multipart/form-data">
                                        <div class="user-photo">
                                            {% csrf_token %}
                                            {% if not user.profile_pic %}
                                                <img id="profile_pic" src="{{ user.profile_pic }}" alt="User Photo">
                                            {% else %}
                                                <img id="profile_pic" src="{{ user.profile_pic.url }}" alt="User Photo">
                                            {% endif %}
                                            {#                                            <input type="file" name="profile_pic" class="user-photo-action"#}
                                            {#                                                   id="reg-form-img" placeholder="Click here to reupload" value="">#}
                                            {#                                            <span class="user-photo-action">Click here to reupload</span>#}
                                        </div><!-- /.user-photo -->
                                    </form>
                                </div><!-- /.widget -->


                                <div class="widget">

                                    <ul class="menu-advanced">
                                        <li><a href="{% url 'member:profile' %}"><i class="fa fa-user"></i> Edit
                                            Profile</a></li>
                                        <li class="active"><a href="{% url 'member:invoice' %}"><i
                                                class="fa fa-file-text-o"></i> Booked's Invoice</a></li>
                                        <li><a href="{% url 'member:logout' %}"><i class="fa fa-sign-out"></i>
                                            Logout</a></li>
                                    </ul>
                                </div><!-- /.widget -->

                            </div><!-- /.sidebar -->
                        </div><!-- /.col-* -->
                        <div class="col-sm-8 col-lg-9">
                            <div class="content">
                                <div class="page-title-superlist">
                                    <h1>{{ user.name }}</h1>
                                </div><!-- /.page-title -->
                                {% if invoices %}
                                    {% for invoice in invoices %}
                                        <div class="background-white box-shadow p20 mb30">
                                            <a id="{{ invoice.bid }}" class="btn_download" href="{% url 'member:invoice_download' invoice.bid %}"><i class="fa fa-arrow-circle-o-down"></i></a>
                                            {% include 'invoice_card.html' %}

                                            <div class="row">
                                                <button data-invoice="{{ invoice.reservation_no }}" name="btn_cancel" class="btn btn-book pull-right" data-toggle="modal" data-target="#{{ invoice.reservation_no }}">Cancel
                                                </button>
                                                <!-- Modal -->
                                                <div class="modal fade" id="{{ invoice.reservation_no }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                <div class="modal-header">
                                                <div class="row">
                                                <div class="col-xs-7 col-sm-7 col-md-7"><h5 class="modal-title" id="exampleModalLabel"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>Are you sure want to do this?</h5>
                                                </div>
                                                <div class="col-xs-5 col-sm-5 col-md-5">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                </div>
                                                </div>
                                                </div>
                                                <div class="modal-body"></div>
                                                <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"    data-dismiss="modal">No</button><a name="{{ invoice.reservation_no }}" href="" class="btn btn-primary">Yes</a>
                                                </div>
                                                </div>
                                                </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    <h1>Book Any Accommodation Now!!!</h1>
                                {% endif %}

                            </div><!-- /.content -->
                        </div><!-- /.col-* -->
                    </div><!-- /.row -->
                </div><!-- /.container -->
            </div><!-- /.main-inner -->
        </div><!-- /.main -->
    </div>

{% endblock %}

{% block ajax_script %}
    <script>

        $(document).ready(function () {

            {% comment %}var total_price = 0;

            $('td[data-name=r_price]').each(function () {
                r_price = $(this).attr('data-price');
                total_price = parseInt(r_price) + total_price;
            });
            console.log(total_price);

            $('td[data-name=t_price]').text('$ ' + total_price);{% endcomment %}

            $('button[name=btn_cancel]').on('click', function () {
                name_item = $(this).attr('data-invoice');
                $("a[name=" + name_item + "]").attr('href', "/cancel_booking/" + name_item);
            });

        });

    </script>
{% endblock %}

{% block footer %}
    {% include 'include/footer.html' %}
{% endblock %}

templates/activity_invoice.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Invoice</title>
{% endblock %}

{% block content %}
    {% include 'include/navbar.html' %}

    <!--page title start-->
    <section class="page-title page-title-center">
        <div class="container">
            <h2 class="text-uppercase">Profile</h2>
        </div>
    </section>
    <!--page title end-->

    <div class="page-wrapper">
        <div class="main">
            <div class="main-inner">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4 col-lg-3">
                            <div class="sidebar">
                                <div class="widget">
                                    <form id="img-form" action="{% url 'member:edit_profile_picture' %}" method="post"
                                          enctype="multipart/form-data">
                                        <div class="user-photo">
                                            {% csrf_token %}
                                            {% if not user.profile_pic %}
                                                <img id="profile_pic" src="{{ user.profile_pic }}" alt="User Photo">
                                            {% else %}
                                                <img id="profile_pic" src="{{ user.profile_pic.url }}" alt="User Photo">
                                            {% endif %}
                                            {#                                            <input type="file" name="profile_pic" class="user-photo-action"#}
                                            {#                                                   id="reg-form-img" placeholder="Click here to reupload" value="">#}
                                            {#                                            <span class="user-photo-action">Click here to reupload</span>#}
                                        </div><!-- /.user-photo -->
                                    </form>
                                </div><!-- /.widget -->


                                <div class="widget">

                                    <ul class="menu-advanced">
                                        <li><a href="{% url 'member:profile' %}"><i class="fa fa-user"></i> Edit
                                            Profile</a></li>
                                        <li class="active"><a href="{% url 'member:invoice' %}"><i
                                                class="fa fa-file-text-o"></i> Booked's Invoice</a></li>
                                        <li><a href="{% url 'member:logout' %}"><i class="fa fa-sign-out"></i>
                                            Logout</a></li>
                                    </ul>
                                </div><!-- /.widget -->

                            </div><!-- /.sidebar -->
                        </div><!-- /.col-* -->
                        <div class="col-sm-8 col-lg-9">
                            <div class="content">
                                <div class="page-title-superlist">
                                    <h1 style="text-transform: uppercase;">{{ user.name }}</h1>
                                </div><!-- /.page-title -->
                                {% if invoices %}
                                    {% for invoice in invoices %}
                                        <div class="background-white box-shadow p20 mb30">
                                            <a id="{{ invoice.bid }}" class="btn_download" href="{% url 'member:activity_invoice_download' invoice.bid %}"><i class="fa fa-arrow-circle-o-down"></i></a>
                                            {% include 'invoice_card_activity.html' %}
                                            <div class="row">
                                                <button data-invoice="{{ invoice.reservation_no }}" name="btn_cancel" class="btn btn-book pull-right" data-toggle="modal" data-target="#{{ invoice.reservation_no }}">Cancel
                                                </button>
                                                <!-- Modal -->
                                                <div class="modal fade" id="{{ invoice.reservation_no }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                <div class="modal-header">
                                                <div class="row">
                                                <div class="col-xs-7 col-sm-7 col-md-7"><h5 class="modal-title" id="exampleModalLabel"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>Are you sure want to do this?</h5>
                                                </div>
                                                <div class="col-xs-5 col-sm-5 col-md-5">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                </div>
                                                </div>
                                                </div>
                                                <div class="modal-body">...</div>
                                                <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary"    data-dismiss="modal">No</button><a name="{{ invoice.reservation_no }}" href="" class="btn btn-primary">Yes</a>
                                                </div>
                                                </div>
                                                </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                {% else %}
                                    <h1>Book Any Activity Now!!!</h1>
                                {% endif %}

                            </div><!-- /.content -->
                        </div><!-- /.col-* -->
                    </div><!-- /.row -->
                </div><!-- /.container -->
            </div><!-- /.main-inner -->
        </div><!-- /.main -->
    </div>

{% endblock %}

{% block ajax_script %}
    <script>

        $(document).ready(function () {

            {% comment %}var total_price = 0;

            $('td[data-name=r_price]').each(function () {
                r_price = $(this).attr('data-price');
                total_price = parseInt(r_price) + total_price;
            });
            console.log(total_price);

            $('td[data-name=t_price]').text('$ ' + total_price);{% endcomment %}

            $('button[name=btn_cancel]').on('click', function () {
                name_item = $(this).attr('data-invoice');
                $("a[name=" + name_item + "]").attr('href', "/cancel_booking_activity/" + name_item);
            });

        });

    </script>
{% endblock %}

{% block footer %}
    {% include 'include/footer.html' %}
{% endblock %}

templates/activity_pdf_invoice.html
{% extends 'pdf_base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Invoice {{ invoice.reservation_no|safe }}</title>
    <style>
        .invoice_wrapper {
            webkit-box-shadow: 0px 0px 2px 0px rgba(0, 0, 0, 0.75);
            -moz-box-shadow: 0px 0px 2px 0px rgba(0, 0, 0, 0.75);
            box-shadow: 0px 0px 2px 0px rgba(0, 0, 0, 0.75);
        }

        @page {
            size: letter portrait;
        }
        h3{
            top: 0;
            float: right;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="invoice_wrapper">
        {% include 'invoice_card_activity.html' %}
    </div>
{% endblock %}

{% comment %}
{% block ajax_script %}
    <script>

        $(document).ready(function () {

            var total_price = 0;

            $('td[data-name=r_price]').each(function () {
                r_price = $(this).attr('data-price');
                total_price = parseInt(r_price) + total_price;
            });
            console.log(total_price);

            $('td[data-name=t_price]').text('$ ' + total_price);

        });

    </script>
{% endblock %}{% endcomment %}

templates/change_pass_email.html
{% autoescape off %}
Hi {{ user.name }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'member:resetpassword' uidb64=uid token=token %}
{% endautoescape %}

templates/item-detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Bungalow</title>
{% endblock %}

{% block content %}
    {% include 'include/navbar.html' %}
{% endblock %}

{% block footer %}
    {% include 'include/footer.html' %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="login login-bg">

        <div class="container">
            <div class="login-logo text-center">
                <a href="{% url 'member:index' %}"> <img class="retina" src="{% static 'img/logo.png' %}" alt=""/></a>
            </div>
            <div class="login-box btn-rounded login-bg-input border-less-input">
                <form id="login-form" name="login-form" class="" action="{% url 'member:login' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="text-center"><h3>LOGIN</h3></div>
                    <p class="text-danger no-margin">{{ error_message }}</p>
                    <div class="form-group">
                        <input type="email" id="login-form-username" name="email" value="" class="form-control" placeholder="Login ID">
                    </div>

                    <div class="form-group">
                        <input type="password" id="login-form-password" name="password" value="" class="form-control " placeholder="Password">
                    </div>

                    <div class="form-group">
                        <button class="btn btn-small btn-dark-solid full-width btn-rounded" id="login-form-submit" name="login-form-submit" value="login">Login</button>
                    </div>
                    {% comment %}<div class="login-social-link">
                        <a href="index.html" class="facebook">
                            Facebook
                        </a>
                        <a href="index.html" class="twitter">
                            Twitter
                        </a>
                    </div>{% endcomment %}

                    <div class="form-group">
                        <input type="checkbox" value="remember-me" id="checkbox1"> <label for="checkbox1">Remember me
                        </label>
                        <label>New User?<a href="{% url 'member:register' %}">Register</a></label>
                        <a class="pull-right" data-toggle="modal" href="{% url 'member:forgotpassword' %}"> Forgot Password?</a>
                    </div>
                </form>
            </div>
            <div class="copyright-row text-center dark-txt">
                Copyrights © All Rights Reserved by  <a href="#" class="theme-color">Kirirom Institute of Technology</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/p_invoice.html
{% extends 'pdf_base.html' %}
{% load staticfiles %}

{% block title %}
    <title>Invoice {{ invoice.reservation_no|safe }}</title>
    <style>
        .invoice_wrapper {
            webkit-box-shadow: 0px 0px 2px 0px rgba(0, 0, 0, 0.75);
            -moz-box-shadow: 0px 0px 2px 0px rgba(0, 0, 0, 0.75);
            box-shadow: 0px 0px 2px 0px rgba(0, 0, 0, 0.75);
        }

        @page {
            size: letter portrait;
        }
        h3{
            top: 0;
            float: right;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="invoice_wrapper">
        {% include 'invoice_card.html' %}
    </div>
{% endblock %}

{% comment %}
{% block ajax_script %}
    <script>

        $(document).ready(function () {

            var total_price = 0;

            $('td[data-name=r_price]').each(function () {
                r_price = $(this).attr('data-price');
                total_price = parseInt(r_price) + total_price;
            });
            console.log(total_price);

            $('td[data-name=t_price]').text('$ ' + total_price);

        });

    </script>
{% endblock %}{% endcomment %}

templates/partial_accommodation_delete.html
<form data-record-id="accommodation-record-id_{{ accommodation.id }}" method="post" action="{% url 'member:accommodation_delete' accommodation.id %}" class="js-accommodation-delete-form" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm accommodation deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the accommodation <strong>{{ accommodation.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Accommodation</button>
  </div>
</form>

templates/partial_accommodation_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

templates/partial_accommodation_list.html
{% for accommodations in accommodation %}
  <tr>
    <td>{{ accommodations.id }}</td>
    <td>{{ accommodations.name }}</td>
    <td>{{ accommodations.type }}</td>
    <td>{{ accommodations.amount }}</td>
    <td>${{ accommodations.price }}</td>
    <td>{{ accommodations.quantity }}</td>
    <td>{{ accommodations.detail }}</td>
    <td>{{ accommodations.image }}</td>
    <td>
      <button type="button" class="btn btn-warning btn-sm js-update-acc" data-url="{% url 'member:accommodation_update' accommodations.id %}"><span class="glyphicon glyphicon-pencil"></span>Edit
      </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="8" class="text-center bg-warning">No Accommodation</td>
  </tr>
{% endfor %}

templates/reset-password.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    <title>vKirirom</title>
{% endblock %}

{% block content %}

    {% comment %}Navbar{% endcomment %}
    {% include 'include/navbar.html' %}

    {% comment %}page header{% endcomment %}
    <div class="page-title page-title-center">
        <div class="container">
            <h2 class="text-uppercase">Reset Password</h2>
        </div>
    </div>

    {% comment %}Content{% endcomment %}
    <div class="page-wrapper">
        <div class="main">
            <div class="main-inner">
                <div class="container">
                    <div class="row">
                        <p class="text-info text-center">
                            Reset your password here!
                        </p>
                    </div>
                    <div class="row">
                        <div class="text-center">
                            <div class="col-md-5">
                                {% if message_error %}
                                    <p class="text-center text-danger">{{ message_error }}</p>
                                {% endif %}
                                <form action="{% url 'member:resetpassword' uidb64=uid token=token %}" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <input type="password" name="password" class="form-control" placeholder="New password">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" name="confirm" class="form-control" placeholder="Re-type password">
                                    </div>
                                    <div class="form-group">
                                        <input class="btn btn-small btn-dark-solid full-width btn-rounded" type="submit" value="Reset">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block footer %}
    {% include 'include/footer.html' %}
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    <title>signup</title>
{% endblock %}


{% block content %}
    <div class="reg reg-bg">
        <div class="container">
            <div class="login-logo text-center">
                 <a href="{% url 'member:index' %}"> <img class="retina" src="{% static 'img/logo.png' %}" alt=""/></a>
            </div>
            <div class="login-box btn-rounded login-bg-input border-less-input">
                <form id="signup-form" class="" action="{% url 'member:register' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="text-center">
                        <h3>Register</h3>
                    </div>
                    <div class="form-group">
                        <input type="text" id="reg-form-username" name="name" class="form-control" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input type="email" id="reg-form-email" name="email" class="form-control" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <input type="number" id="reg-form-pnum" name="phone" class="form-control" placeholder="Phone Number">
                    </div>
                    <div class="form-group">
                        <input type="password" id="reg-form-password" name="password" class="form-control" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input type="password" id="reg-form-confirm" name="confirm" class="form-control" placeholder="Confirm Password">
                    </div>
                    <div class="form-group">
                        <select name="validation_type" id="reg-form-imgvalid" class="form-control">
                            <option value="IDC">Identity Card</option>
                            <option value="PSP">PASSPORT</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="file" id="reg-form-img" name="validation_img" class="form-control" placeholder="Please choose your image">
                    </div>
                    <div class="form-group">
                        <input type="" class="form-control" placeholder="Please choose your image">
                    </div>
                    <div class="form-group">
                        <button class="btn btn-small btn-dark-solid full-width btn-rounded" id="reg-form-submit" name="reg-form-submit" value="Register">Register</button>
                    </div>
                </form>
            </div>
            <div class="copyright-row text-center dark-txt">
                Copyrights © All Rights Reserved by  <a href="#" class="theme-color">Kirirom Institute of Technology</a>
            </div>
        </div>
    </div>
{% endblock %}